name: Deploy to Railway

on:
  push:
    branches:
      - main  # Or change to the branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Basic Test (Optional)
      run: |
        echo "✅ No unit tests configured yet. Proceeding with deployment."

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
      run: |
        curl -X POST https://backboard.railway.app/project/531c5739-f6a2-4051-8f80-92c9c0c3a11a/deploy \
        -H "Authorization: Bearer $RAILWAY_TOKEN"
